language: node_js
node_js: stable
branches:
  only:
  - blog_source
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_43fe3767f1a1_key -iv $encrypted_43fe3767f1a1_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "SunshineABC"
- git config --global user.email "dealloc@sina.cn"
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
- git clone -b mod https://github.com/SunshineABC/next.git themes/next
script:
- hexo clean
- hexo g

after_success:
- hexo deploy